# Generated by Django 4.2.1 on 2023-06-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dietNum', models.AutoField(primary_key=True, serialize=False, verbose_name='Diet Number')),
                ('dietName', models.CharField(max_length=255, verbose_name='Diet Name')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('dailyCalories', models.IntegerField(verbose_name='Calorie target')),
                ('targetWeight', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Target weight')),
            ],
        ),
        migrations.CreateModel(
            name='Dietician',
            fields=[
                ('dieticianNum', models.AutoField(primary_key=True, serialize=False, verbose_name='Dietician Number')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('foodDocId', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Food Doc Id')),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patNum', models.AutoField(primary_key=True, serialize=False, verbose_name='Patient Number')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('checkedIn', models.BooleanField()),
                ('gender', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=1)),
                ('height', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealNum', models.AutoField(primary_key=True, serialize=False, verbose_name='Meal Number')),
                ('mealName', models.CharField(max_length=255)),
                ('dietNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.diet', verbose_name='Diet')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemMealMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.fooditem', verbose_name='Food Item')),
                ('mealNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.meal', verbose_name='Meal')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='dieticianId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.dietician', verbose_name='Dietician'),
        ),
        migrations.AddField(
            model_name='diet',
            name='patNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.patient', verbose_name='Patient'),
        ),
    ]
