# Generated by Django 4.2.1 on 2023-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='dietNum',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='patNum',
            new_name='patientId',
        ),
        migrations.RenameField(
            model_name='dietician',
            old_name='dieticianNum',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='foodDocId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fooditemmealmap',
            old_name='foodItem',
            new_name='foodItemId',
        ),
        migrations.RenameField(
            model_name='fooditemmealmap',
            old_name='mealNum',
            new_name='mealId',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='mealNum',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patNum',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='fooditemmealmap',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Food Item Meal Id'),
        ),
    ]
